function buildAdminForm(){
	var code = $('#AdminPage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	code.show();
	code.val('<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Admin Form: "' + oName + '" Object -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<!--Recommended include -->\r\n');
	code.val( code.val() + '<link rel="stylesheet" href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" />\r\n');
	code.val( code.val() + '<script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>\r\n');
	
	
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	
	code.val( code.val() + '<fieldset>\r\n');
	code.val( code.val() + tab(1) + '<legend>' + oName + '</legend>\r\n');
	code.val( code.val() + tab(2) + '<table id="tbl_'+ oName + 's" class="dataTable display" cellspacing="0" width="100%">\r\n');
	code.val( code.val() + tab(3) +	'<thead>\r\n');
	code.val( code.val() + tab(4) +	'<tr>\r\n');
	
	//iterate through attribute's labels
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		code.val( code.val() + tab(5) +	'<th>' + label + '</th>\r\n');
	});
	code.val( code.val() + tab(5) +	'<th>Controls</th>\r\n');
	//end iteration
	
	code.val( code.val() + tab(4) +	'</tr>\r');
    code.val( code.val() + tab(3) +	'</thead>\r');
    code.val( code.val() + tab(3) +	'<tbody>\r');
	//ouput Data
	code.val( code.val() + tab(4) +	'<?php\r\n');
	code.val( code.val() + tab(5) +	'$conn = getConnection();\r\n');
	code.val( code.val() + tab(5) +	'$query = "SELECT * FROM `' + oName + '`";\r\n');
	code.val( code.val() + tab(5) +	'$result = $conn->prepare($query);\r\n');
	code.val( code.val() + tab(5) +	'foreach( $result->fetchAll(PDO::FETCH_ASSOC) as $row){\r\n');
	code.val( code.val() + tab(6) +	'echo "<tr>";\r\n');
	
	$('#formMode .formSection').each(function(){
		var name = $(this).find('.item_variableName input').val();
		name = name.replace(/\s+/g, ' ');
		code.val( code.val() + tab(7) +	'echo "<td>".$row["' + name + '"]."</td>";\r\n');
	});
	
	
	code.val( code.val() + tab(6) +	'?>\r\n');
	code.val( code.val() + tab(7) +	'<td>\r\n');
	//custom links
	code.val( code.val() + tab(8) +	'<a href="modify' + oName + '.php?' + oName + 'ID=<?php echo $row["id"]; ?>">Modify</a> <a href="Delete' + oName + '.php?' + oName + 'ID=<?php echo $row["id"]; ?>">Delete</a>\r\n');
	
	code.val( code.val() + tab(7) +	'</td>\r\n');
	code.val( code.val() + tab(6) +	'<?php\r\n');
	code.val( code.val() + tab(6) +	'echo "</tr>";\r\n');
	code.val( code.val() + tab(5) +	'}\r\n');
	code.val( code.val() + tab(4) +	'?>\r\n');
	//end output data
    code.val( code.val() + tab(3) +	'</tbody>\r\n');
	code.val( code.val() + tab(3) +	'<tfoot>\r\n');
	code.val( code.val() + tab(4) +	'<tr>\r\n');
	
	//iterate through attributes's labels
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		code.val( code.val() + tab(5) +	'<th>' + label + '</th>\r\n');
	});
	code.val( code.val() + tab(5) +	'<th>Controls</th>\r\n');
	//end iteration
	
	code.val( code.val() + tab(4) +	'</tr>\r\n');
	code.val( code.val() + tab(3) +	'</tfoot>\r\n');				
	code.val( code.val() + tab(2) +	'</table>\r\n');				
	code.val( code.val() + '</fieldset>\r\n');
	
	//javascript enabling
	code.val( code.val() + '<script type="text/javascript">\r\n');
	code.val( code.val() + tab(2) +	'$(function(){\r\n');
	code.val( code.val() + tab(3) +	'/* Optional Configurations commented out */\r\n');
	code.val( code.val() + tab(3) +	'$("#tbl_'+ oName + 's").DataTable({\r\n');	
	code.val( code.val() + tab(4) +	'//"processing": true,\r\n');	
	code.val( code.val() + tab(4) +	'//"serverSide": false,\r\n');	
	code.val( code.val() + tab(4) +	'//"ajax": "/admin/' + oName + '_table.php",\r\n');	
	code.val( code.val() + tab(4) +	'//"columns" :  [ {"name": "0", "orderable": "true"}, {"name": "1", "orderable": "true"}, {"name": "2", "orderable": "true"}, {"name": "3", "orderable": "true"} ]\r\n');	
	code.val( code.val() + tab(3) +	'});\r\n');
	code.val( code.val() + tab(2) +	'});\r\n');	
	code.val( code.val() + '</script>\r\n');
	

	makeCodeEditor('AdminPage');
}

function buildCreateForm(){
	var code = $('#CreatePage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	code.show();
	code.val('<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Create Form: "' + frmName.capitalize() + '" Object -->\r\n');
	
	
	makeCodeEditor('CreatePage');
}

function buildUpdateForm(){
	var code = $('#UpdatePage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	code.show();
	code.val('<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Update Form: "' + frmName.capitalize() + '" Object -->\r\n');
	
	
	makeCodeEditor('UpdatePage');
}

function buildDeleteForm(){
	var code = $('#DeletePage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	code.show();
	code.val('<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Delete Form: "' + frmName.capitalize() + '" Object -->\r\n');
	
	
	makeCodeEditor('DeletePage');
}