function onlyUnique(value, index, self) { 
    return self.indexOf(value) === index;
}


function buildInclude(){
	var code = $('#generatedConn');
	code.show();
	code.val('<?php\r\n');
	code.val( code.val() + tab(1) + '//some instances may bark if date isn\'t set\r\n');
	code.val(  code.val() + tab(1) + 'date_default_timezone_set("America/New_York");\r\n');

	code.val( code.val() + tab(1) + 'function getConnection() {\r\n');
		
	code.val( code.val() + tab(2) + '$dbName = "localDB"; 			//Database Name\r\n');
	code.val( code.val() + tab(2) + '$dbUser = "localUser"; 			//Database User\r\n');
	code.val( code.val() + tab(2) + '$dbPass = "awesomePassword"; 	//Database Password\r\n');
	code.val( code.val() + tab(2) + '$dbHost = "localhost";\r\n');
		
	code.val( code.val() + tab(2) + '$dbc = null;\r\n');
	code.val( code.val() + tab(2) + 'try {\r\n');
	code.val( code.val() + tab(3) +	"$dbc = new PDO('mysql:host='.$dbHost.';dbname='.$dbName, $dbUser, $dbPass);\r\n");
	code.val( code.val() + tab(3) +	'$dbc->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );\r\n');
	code.val( code.val() + tab(2) + '}\r\n');
	code.val( code.val() + tab(2) + 'catch(PDOException $e) {\r\n');
	code.val( code.val() + tab(3) +	'echo "<h2>An error has occurred connecting to the database</h2>";\r\n');
	code.val( code.val() + tab(3) +	'echo "<p>".$e->getMessage()."</p>";\r\n');
	code.val( code.val() + tab(3) +	"file_put_contents('PDOErrorsLog.txt', $e->getMessage(), FILE_APPEND);\r\n");
	code.val( code.val() + tab(2) + '}\r\n');
	code.val( code.val() + tab(2) + 'return $dbc;\r\n');
	code.val( code.val() + tab(1) + '}\r\n');

	
	console.log("Header Footer:" + $('#headerfooter').prop('checked') );
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + '\r\n');
		code.val( code.val() + tab(1) + 'function getHeader() {\r\n');
		code.val( code.val() + tab(2) + '/*Stub Header Function*/\r\n');
		
	
		code.val( code.val() + tab(2) + '?>\r\n');
		code.val( code.val() + tab(2) + '<html>\r\n');
		code.val( code.val() + tab(3) + '<head>\r\n');
		code.val( code.val() + tab(4) + '<title></title>\r\n');
		code.val( code.val() + tab(4) + '<script   src="//code.jquery.com/jquery-1.12.3.js"   crossorigin="anonymous"></script>\r\n');
		code.val( code.val() + tab(4) + '<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />\r\n');
		code.val( code.val() + tab(4) + '<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>\r\n');	
		code.val( code.val() + tab(3) + '</head>\r\n');
		code.val( code.val() + tab(3) + '<body>\r\n');
		code.val( code.val() + tab(2) + '<?php\r\n');
		
		
		code.val( code.val() + tab(1) + '}\r\n');
		code.val( code.val() + '\r\n');
		code.val( code.val() + tab(1) + 'function getFooter() {\r\n');
		code.val( code.val() + tab(2) + '/*Stub Footer Function*/\r\n');
	
		code.val( code.val() + tab(2) + '?>\r\n');
		code.val( code.val() + tab(3) + '</body>\r\n');
		code.val( code.val() + tab(2) + '</html>\r\n');
		code.val( code.val() + tab(2) + '<?php\r\n');
	
		code.val( code.val() + tab(1) + '}\r\n');
	}



	code.val( code.val() + '\r\n');
	code.val( code.val() + '?>');
}

function buildAdminForm(){
	var code = $('#AdminPage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	code.show();
	code.val( code.val() + '<?php\r\n');
	if( $('#headerfooter').prop('checked') == true ){
		
		code.val( code.val() + tab(1) +	'include "include.php";\r\n');
		code.val( code.val() + tab(1) + 'getHeader();\r\n');
		
	}else{
		code.val( code.val() + tab(1) +	'include "include.php";\r\n');
	}
	code.val( code.val() + '?>\r\n');	
	code.val( code.val() + '<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Admin Form: "' + oName + '" Object -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<!-- ' + oName + 'Admin.php -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	
	if( !$('#headerfooter').prop('checked') ){
		code.val( code.val() + '<!--Recommended include -->\r\n');
		code.val( code.val() + '<script   src="//code.jquery.com/jquery-1.12.3.js"   crossorigin="anonymous"></script>\r\n');
		code.val( code.val() + '<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />\r\n');
		code.val( code.val() + '<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>\r\n');
	}
	
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<p><a href="create' + oName + '.php">Create New ' + oName + '</a></p>');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<fieldset>\r\n');
	code.val( code.val() + tab(1) + '<legend>' + oName + '</legend>\r\n');
	code.val( code.val() + tab(2) + '<table id="tbl_'+ oName + 's" class="dataTable display" cellspacing="0" width="100%">\r\n');
	code.val( code.val() + tab(3) +	'<thead>\r\n');
	code.val( code.val() + tab(4) +	'<tr>\r\n');
	
	var buildHF = "<th>ID</th>";
	
	//iterate through attribute's labels
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		if( $('#buildAjax').prop('checked') == true  ){
			if( $(this).find('input[name="showAdmin"]').prop('checked') == true ){
				//code.val( code.val() + tab(5) +	'<th>' + label + '</th>\r\n');	
				buildHF += '<th>' + label + '</th>';
			}
		}else{
			//code.val( code.val() + tab(5) +	'<th>' + label + '</th>\r\n');
			buildHF += '<th>' + label + '</th>';
		}
		
	});
	code.val( code.val() + tab(5) + buildHF + '\r\n');
	
	code.val( code.val() + tab(5) +	'<th>Controls</th>\r\n');
	//end iteration
	
	code.val( code.val() + tab(4) +	'</tr>\r');
    code.val( code.val() + tab(3) +	'</thead>\r');
    code.val( code.val() + tab(3) +	'<tbody>\r');
	//ouput Data
	code.val( code.val() + tab(4) +	'<?php\r\n');
	
	code.val( code.val() + tab(5) +	'$conn = getConnection();\r\n');
	if( $('#buildAjax').prop('checked') == true  ){
		//values will auto load
		code.val( code.val() + tab(7) +	'?>\r\n');
	}else{
		code.val( code.val() + tab(5) +	'$query = "SELECT * FROM `' + frmName + '`";\r\n');
		code.val( code.val() + tab(5) +	'$result = $conn->prepare($query);\r\n');
		code.val( code.val() + tab(5) +	'if( $result->execute() ) {\r\n');
		code.val( code.val() + tab(6) +	'foreach( $result->fetchAll(PDO::FETCH_ASSOC) as $row){\r\n');
		code.val( code.val() + tab(7) +	'echo "<tr>";\r\n');
		
		$('#formMode .formSection').each(function(){
			var name = $(this).find('.item_variableName input').val();
			name = name.replace(/\s+/g, ' ');
			code.val( code.val() + tab(8) +	'echo "<td>".$row["' + name + '"]."</td>";\r\n');
		});
		
		
		code.val( code.val() + tab(7) +	'?>\r\n');
		code.val( code.val() + tab(7) +	'<td>\r\n');
		//custom links
		code.val( code.val() + tab(9) +	'<a href="modify' + oName + '.php?' + frmName + 'ID=<?php echo $row["id"]; ?>">Modify</a> <a href="delete' + oName + '.php?' + frmName + 'ID=<?php echo $row["id"]; ?>">Delete</a>\r\n');
		
		code.val( code.val() + tab(8) +	'</td>\r\n');
		code.val( code.val() + tab(7) +	'<?php\r\n');
		code.val( code.val() + tab(7) +	'echo "</tr>";\r\n');
		code.val( code.val() + tab(6) +	'}\r\n');
		code.val( code.val() + tab(5) +	'}\r\n');
		code.val( code.val() + tab(4) +	'?>\r\n');
	}
	//end output data
    code.val( code.val() + tab(3) +	'</tbody>\r\n');
	code.val( code.val() + tab(3) +	'<tfoot>\r\n');
	code.val( code.val() + tab(4) +	'<tr>\r\n');
	
	/****Apply same code as header!!! ******************/
	
	
	//iterate through attributes's labels
	/*
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		code.val( code.val() + tab(5) +	'<th>' + label + '</th>\r\n');
	});
	*/
	code.val( code.val() + tab(5) + buildHF + '\r\n');
	
	code.val( code.val() + tab(5) +	'<th>Controls</th>\r\n');
	//end iteration
	
	code.val( code.val() + tab(4) +	'</tr>\r\n');
	code.val( code.val() + tab(3) +	'</tfoot>\r\n');				
	code.val( code.val() + tab(2) +	'</table>\r\n');				
	code.val( code.val() + '</fieldset>\r\n');
	
	code.val( code.val() + '<a href="export' + oName + '.php">Download Data in CSV Format</a>\r\n');
	
	
	//javascript enabling
	code.val( code.val() + '<script type="text/javascript">\r\n');
	code.val( code.val() + tab(2) +	'$(function(){\r\n');
	code.val( code.val() + tab(3) +	'/* Optional Configurations commented out */\r\n');
	code.val( code.val() + tab(3) +	'$("#tbl_'+ oName + 's").DataTable({\r\n');	
	
	if(  $('#buildAjax').prop('checked') == true ){
	
	code.val( code.val() + tab(4) +	'"processing": true,\r\n');	
	code.val( code.val() + tab(4) +	'"serverSide": true,\r\n');	
	code.val( code.val() + tab(4) +	'"ajax": "ajaxTable' + oName + '.php",\r\n');	
	code.val( code.val() + tab(4) +	'//"columns" :  [ {"name": "0", "orderable": "true"}, {"name": "1", "orderable": "true"}, {"name": "2", "orderable": "true"}, {"name": "3", "orderable": "true"} ]\r\n');	
	
	}
	
	
	code.val( code.val() + tab(3) +	'});\r\n');
	code.val( code.val() + tab(2) +	'});\r\n');	
	code.val( code.val() + '</script>\r\n');
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + '<?php\r\n');
		code.val( code.val() + tab(1) + 'getFooter();\r\n');
		code.val( code.val() + '?>\r\n');
	}
	

	makeCodeEditor('AdminPage', 'text/html');
}


function getFormInnards(code, frmName){
	var frmName = $('#className').val().toLowerCase().trim();
	var variables = $('#variables');
	var code = $('#' + code );
	
	
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		var variable = $(this).find('.item_variableName input').val();
		variable = variable.replace(/\s+/g, ' ');
		var type =  $(this).find('.item_type select option:selected').val();
		var required = $(this).find('.item_required input').prop('checked');
		var restrictLength = $(this).find('.type_text input[name="item_restrictLength"]').prop('checked');
		var min = 0;
		var max = 0;
		var errText = $(this).find('.item_error input').val();
		var restrictAmount =  $(this).find('.type_number input[name="item_restrictAmount"]').prop('checked');
		var minAmount = 0;
		var maxAmount = 0;
		var pattern =  $(this).find('.type_pattern textarea').val();
		var placeHolder = "";
		var restrictDate= $(this).find('.item_date input[name="item_restrictDates"]').prop('checked');
		
		var list_type = $(this).find(' .type_list > input[type="radio"]:checked').val();
		
		var listObjectName = $(this).find('.type_list  .objectDetails input[name="objectName"]').val();
		var listObjectKeyFunction = $(this).find('.type_list  .objectDetails input[name="objectKey"]').val();
		var listObjectTitleFunction = $(this).find('.type_list  .objectDetails input[name="objectTitle"]').val();
		//
		//console.log("Oname: " + listObjectName +" OKey:" + listObjectKeyFunction + " OTitle" + listObjectTitleFunction);
		
		if( variable == "" ){
			return;
		}
		
		if( errText == "" ){
			if( required ){
				errText = label + " is a required field. ";
			}
		}
		
		if( restrictLength ){
			min = $(this).find('.type_text input[name="min_length"]').val();
			max = $(this).find('.type_text input[name="max_length"]').val();
			errText += label + " must be between " + min + " and " + max + " characters in length. ";
		}
		
		
		if( restrictAmount ){
			minAmount = $(this).find('.type_number input[name="min_amount"]').val();
			maxAmount = $(this).find('.type_number input[name="max_amount"]').val();
			errText += label + " must have a value between " + minAmount + " and " + maxAmount + ". ";
		}
		
		
		code.val( code.val() + tab(1) + '<div class="formRow">' );
		code.val( code.val() + tab(2) + '<div class="rowLabel">' );
		code.val( code.val() + tab(3) + '<label for="' + variable + '">' + label + ':' + (required ? '*' : '' ) + '</label>');
		code.val( code.val() + tab(2) + '</div>' );
		code.val( code.val() + tab(2) + '<div class="rowField">' );
		
		if( type == "text" ){
			/*Input type text*/
			code.val( code.val() + tab(3) + '<input type="text" name="' + variable + '" id="' + variable + '" value="<?php echo (isset($' + frmName + ') ?  $' + frmName + '->get' + variable.capitalize() + '() : \'\'); ?>" ' + (restrictLength ? 'pattern=".{' + min + ',' + max + '}"' : '') + ' title="' + errText + '" ' +  (required ? 'required="required"' : '' ) + '/>');
			variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
		}else if( type == "number" ){
			/*Number */
			code.val( code.val() + tab(3) + '<input type="number" name="' + variable + '" id="' + variable + '" value="<?php echo (isset($' + frmName + ') ?  $' + frmName + '->get' + variable.capitalize() + '() : \'\'); ?>" ' + (restrictLength ? 'pattern=".{' + min + ',' + max + '}" ' : '') + 'title="' + errText + '" ' + (required ? 'required="required" ' : '') +  (restrictAmount ? 'min="' + minAmount + '" max="' + maxAmount + '"' : '') +'/>');
			variables.val( variables.val() + '\r\n' + variable +', ' + 'i');
		}else if( type == "email" ){
			/*Email - essentially same as input*/
			if( required ){
				errText = label + " is a required field. ";
			}
			code.val( code.val() + tab(3) + '<input type="email" name="' + variable + '" id="' + variable + '" value="<?php echo (isset($' + frmName + ') ?  $' + frmName + '->get' + variable.capitalize() + '() : \'\'); ?>" ' + (restrictLength ? 'pattern=".{' + min + ',' + max + '}" ' : '') + 'title="' + errText + '" ' + (required ? 'required="required" ' : '')  + '/>');
			
			variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
		}else if( type == "textarea" || type == "wysiwyg" ){
		
			/*Textarea*/
			
			code.val( code.val() + tab(3) + '<textarea ' + (type == "wysiwyg" ? 'class="wysiwyg" ' : '') + ' name="' + variable + '" id="' + variable + '" ' + (required ? ' required="required" ' : '') + (restrictLength ? ' maxlength=' + max + ' minlength=' + min : '') + ' title="' + errText + '" ' + '><?php echo (isset($' + frmName + ') ?  $' + frmName + '->get' + variable.capitalize() + '() : \'\'); ?></textarea>');
			
			
			variables.val( variables.val() + '\r\n' + variable +', ' + 'mt');
			
			
		}else if(type == "select"){
			

			if( list_type == "textarea"){
			
				//set values for select
				var vals =  $(this).find('.type_list textarea').val();
				var valStr = "";
				vals = vals.split(",");
				for(var v=0; v < vals.length; v++){
					valStr += '"' + vals[v] + '"';
					if( ((v + 1) < vals.length) ){
					valStr += ', '
					}
				}
				//get variable
				code.val( code.val() + tab(3) + '<?php $' + variable + '_values = array(' + valStr + '); ?>');	
				code.val( code.val() + tab(3) + '<?php if( isset( $' + frmName + ') && $' + frmName +'->get' + variable.capitalize() + '() != null ){');
				code.val( code.val() + tab(4) + ' $' + variable + '_selected = $' + frmName +'->get' + variable.capitalize() + '();');
				code.val( code.val() + tab(3) + '}else{');
					code.val( code.val() + tab(4) + ' $' + variable + '_selected = "";');
				code.val( code.val() + tab(3) + '} ?>');
				
				
				code.val( code.val() + tab(3) + '<select name="' + variable  + '"' + (required ? ' required="required" ' : '') +'>');
				code.val( code.val() + tab(4) + '<?php for($v=0; $v < sizeof($' + variable + '_values); $v++){ ?>');
				code.val( code.val() + tab(5) + '<option value="<?php echo $'+ variable +'_values[$v]; ?>" <?php if($'+ variable +'_values[$v] ==  $' + variable + '_selected ){ echo "selected"; } ?>><?php echo $'+ variable +'_values[$v]; ?></option>' );
				code.val( code.val() + tab(4) + '<?php } ?>');
				code.val( code.val() + tab(3) + '</select>');
				
				variables.val( variables.val() + '\r\n' + variable +', ' + 'i');
			
			}else if(list_type == "object"){
				
				variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
				
				
				
				/*In progress */
				code.val( code.val() + tab(3) + '<?php');
				
				code.val( code.val() + tab(4) + '// $conn = getConnection();');
				code.val( code.val() + tab(4) + '// include "' +  listObjectName.capitalize() + '.php";');
				code.val( code.val() + tab(4) + '// $' + listObjectName + ' = new ' + listObjectName.capitalize() + '($conn); ');
				code.val( code.val() + tab(4) + '$query = $conn->prepare("SELECT `' +  listObjectKeyFunction + '`, `' + listObjectTitleFunction + '` FROM `' + listObjectName + '`");');
			
				code.val( code.val() + tab(3) + '?>');
				
				//code.val( code.val() + tab(3) + 'Objecterino!!');
				
				code.val( code.val() + tab(3) + '<select name="' + variable  + '"' + (required ? ' required="required" ' : '') +'>');
				code.val( code.val() + tab(3) + '<?php');
				code.val( code.val() + tab(4) + '$default = isset($' + frmName + ') ? $' + frmName + '->get' + variable.capitalize() + '() : "' + placeHolder + '";');
				
				code.val( code.val() + tab(4) + 'if( $query->execute() ){');
				code.val( code.val() + tab(5) + 'while( $result = $query->fetchObject("' + listObjectName.capitalize() + '") ){');
				code.val( code.val() + tab(6) + "if( $default == $result->get" + listObjectKeyFunction.capitalize() + "() ){");		
				code.val( code.val() + tab(7) + "echo '<option value=\"'.$result->get" + listObjectKeyFunction.capitalize() + "().'\" selected>'.$result->get" + listObjectTitleFunction.capitalize() + "().'</option>';");	
				code.val( code.val() + tab(6) + "}else{");
				code.val( code.val() + tab(7) + "echo '<option value=\"'.$result->get" + listObjectKeyFunction.capitalize() + "().'\">'.$result->get" + listObjectTitleFunction.capitalize() + "().'</option>';");	
				code.val( code.val() + tab(6) + "}");
				
				
				code.val( code.val() + tab(5) + '}');

				code.val( code.val() + tab(4) + '}');
				
				code.val( code.val() + tab(3) + '?>');
				//code.val( code.val() + tab(5) + '<option value="incomplete">Need to implement</option>');
				
				code.val( code.val() + tab(3) + '</select>');
				
			}
			
			
			
			
		}else if( type == "checkbox" ){
			
			code.val( code.val() + tab(3) + '<?php if( isset( $' + frmName + ') && $' + frmName +'->get' + variable.capitalize() + '() != null ){');
			code.val( code.val() + tab(4) + ' $' + variable + '_selected = $' + frmName +'->get' + variable.capitalize() + '();');
			code.val( code.val() + tab(3) + '}else{');
				code.val( code.val() + tab(4) + ' $' + variable + '_selected = "";');
			code.val( code.val() + tab(3) + '} ?>');
			
			code.val( code.val() + tab(3) + '<input type="checkbox" id="' + variable + '" name="' + variable + '" ' + ' title="' + errText + '" ' + (required ? ' required="required" ' : '') + ' value="1" <?php if($' + variable + '_selected == 1 ){ echo "checked"; } ?> />');

			//variable length should be size of largest option
			variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
		}else if(type == "pattern" ){
		
			code.val( code.val() + tab(3) + '<input type="text" id="' + variable + '" name="' + variable + '" ' + ' title="' + errText + '" ' + (required ? ' required="required" ' : '') + ' pattern="' + pattern + '" value="<?php echo (isset($' + frmName + ') ?  $' + frmName + '->get' + variable.capitalize() + '() : \'\'); ?>" />');
		
			variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
		
		}else if (type == "selectMultiple" || type == "radioGroup" || type == "checkGroup" ){
			
			////////////////
			
			
			
			var vals =  $(this).find('.type_list textarea').val();
			var valStr = "";
			vals = vals.split(",");
			for(var v=0; v < vals.length; v++){
				valStr += '"' + vals[v] + '"';
				if( ((v + 1) < vals.length) ){
				valStr += ', '
				}
				
				//create multiple variables for these
				if( type == "selectMultiple" || type == "checkGroup" ){
					variables.val( variables.val() + '\r\n' + variable +'_' + v + ', ' + 'v');
				}
				
			}
			code.val( code.val() + tab(3) + '<?php $' + variable + '_values = array(' + valStr + '); ?>');	
			
			if( type == "selectMultiple" ){
				code.val( code.val() + tab(3) + '<select id="' + variable + '" name="' + variable + '[]" ' + ' title="' + errText + '" ' + (required ? ' required="required" ' : '') + ' multiple>');
			
				code.val( code.val() + tab(4) + '<?php for($sm = 0; $sm < sizeof( $' + variable + '_values); $sm++){ ?>');
				
				//get values
				
				code.val( code.val() + tab(5) + '<?php $function = "get' +  variable.capitalize() + '_' + '".$sm; ?>');
				
				code.val( code.val() + tab(5) + '<option value="<?php echo $'+ variable +'_values[$sm]; ?>" <?php if($'+ variable +'_values[$sm] ==  ( is_object($' + frmName + ') &&  $' + frmName + '->$function() ?  $' + frmName + '->$function()  : \'\') ){ echo "selected"; } ?>><?php echo $'+ variable +'_values[$sm]; ?></option>' );
			
				code.val( code.val() + tab(4) + '<?php } ?>');
				code.val( code.val() + tab(3) + '</select>');
				code.val( code.val() + tab(3) + '<p>You may hold ctrl to select multiple items</p>');
				
				//added vars for each
				
			
			}else if( type == "checkGroup" ){
				
				code.val( code.val() + tab(3) + '<?php for($sm = 0; $sm < sizeof( $' + variable + '_values); $sm++){ ?>');
				code.val( code.val() + tab(4) + '<?php $function = "get' +  variable.capitalize() + '_' + '".$sm; ?>');
				
				code.val( code.val() + tab(4) + '<label><?php echo $' + variable + '_values[$sm]; ?>: <input type="checkbox" name="' + variable + '_<?php echo $sm; ?>" id="' + variable + '_<?php echo $sm; ?>" value="<?php echo trim($' + variable + '_values[$sm]); ?>" <?php if(  ( isset($' + frmName + ') &&  is_object($' + frmName + ') &&  $' + frmName + '->$function() ?  $' + frmName + '->$function()  : \'\') == trim($' + variable + '_values[$sm])){ echo " checked" } ?>/></label>');
			
			
				code.val( code.val() + tab(3) + '<?php } ?>');
			}else if( type == "radioGroup" ){
			
				code.val( code.val() + tab(3) + '<?php for($sm = 0; $sm < sizeof( $' + variable + '_values); $sm++){ ?>');
				//code.val( code.val() + tab(4) + '<?php $function = "get' +  variable.capitalize() + '_' + '".$sm; ?>');
				
				code.val( code.val() + tab(4) + '<label><?php echo $' + variable + '_values[$sm]; ?>: <input type="radio" name="' + variable + '" id="' + variable + '" value="<?php echo trim($' + variable + '_values[$sm]); ?>" <?php if( ( is_object($' + frmName + ') &&  $' + frmName + '->get' +  variable.capitalize() + '() ?  $' + frmName + '->get' +  variable.capitalize() + '()  : \'\') == trim($' + variable + '_values[$sm])){ echo " checked"; } ?> ' + (required ? ' required="required" ' : '') + '/></label>');
			
			
				code.val( code.val() + tab(3) + '<?php } ?>');
			
				variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
			}
			
		
		}else if(type == "date"){
			//pattern="\d{1,2}/\d{1,2}/\d{4}"
			//(mm/dd/yyyy)
			errText = errText + " Date should be in format mm\/dd\/yyyy";
			
			code.val( code.val() + tab(3) + '<label>(mm/dd/yyyy) <input class="dateInput" type="text" name="' + variable + '" id="' + variable + '" value="<?php echo (isset($' + frmName + ') ?  $' + frmName + '->get' + variable.capitalize() + '() : \'\'); ?>" title="' + errText + '" ' +  (required ? 'required="required"' : '' ) + ' pattern="\d{1,2}/\d{1,2}/\d{4}" /></label>');
			
			if( restrictDate ){
				var startYr = $(this).find('.item_date input[name="startYr"]').val();
				var From = $(this).find('.item_date input[name="from"]').val();
				var To = $(this).find('.item_date input[name="to"]').val();
			
				//to do
			
			}
			
			
			
			variables.val( variables.val() + '\r\n' + variable +', ' + 'v');
		}
		
		
		
		
		
		code.val( code.val() + tab(2) + '</div>' );
		
		
		
		code.val( code.val() + tab(1) + '</div>' );
		//console.log(label,variable,type, required, restrictLength, errText, min, max);
		
		//set the class creator to 
		
		
	});
	
	return code;
}	


function buildCreateForm(){
	var code = $('#CreatePage');
	
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	code.show();
	
	code.val( '<?php\r\n');
	code.val( code.val() + tab(1) +	'include "include.php";\r\n');
	code.val( code.val() + tab(1) +	'include "' + oName + '.php";\r\n');
	
	//check if any instances of list and see if any unique classes need to be added !!!!!!!!!!!!!!!
	
	var potentialIncludes =[];
	$('#formMode .formSection').each(function(){
		//select, selectMultiple, RadioButton Group, CheckBoxGroup
		var s = $(this).find('.item_type select[name="item"] option:selected').val(); 
		//console.log( s );
		if( s == "select" || s == "selectMultiple" || s == "radioGroup" || s == "checkGroup" ){
			var t = $(this).find('.type_list input[type="radio"]:checked').val(); 
			//console.log( t );
			if( t == "object"){
				var o = $(this).find('.type_list input[name="objectName"]').val(); 
				//console.log( o );
				if( o != ""){
					potentialIncludes.push(o);
				}
				
			}
		}
	});
	if( potentialIncludes.length > 0){
		var unique = potentialIncludes.filter( onlyUnique );
		for(var i =0; i < unique.length; i++){
			code.val( code.val() + tab(1) +	'include "' + unique[i] + '.php";\r\n');
		}
	}
	
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + tab(1) + 'getHeader();\r\n');
	}	
		
	code.val( code.val() + '?>\r\n');
	
	
	
	
	code.val( code.val() + '<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Create Form: "' + oName + '" Object -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<!-- create' + oName + '.php -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	
	
	

	
	
	
	code.val( code.val() + '<?php\r\n');
	code.val(  code.val() + tab(1) + '$conn = getConnection(); //set to DB Conn');
	code.val(  code.val() + tab(1) + '$' + frmName + ' = new ' + oName + '($conn);');
	code.val(  code.val() + tab(1) + '$showForm = 1;');
	
	code.val(  code.val() + tab(1) + 'if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {');
	code.val(  code.val() + tab(2) + '$' + frmName + '->getFromPost();');
	
	code.val(  code.val() + tab(2) + 'if( $' + frmName + '->save() > 0 && $' + frmName + '->getErrorCount() == 0){');
	
	code.val(  code.val() + tab(3) + 'echo "<p>' + oName + ' saved successfully!</p>";'); 
	code.val(  code.val() + tab(3) + 'echo "<p><a href=\'create' + oName + '.php\'>Add another' + oName + '</a> or <a href=\'' + oName + 'Admin.php\'>Go back to ' + oName + ' management area</a></p>";'); 
	
	
	code.val(  code.val() + tab(3) + '$showForm = 0;');
	code.val(  code.val() + tab(2) + '}else{');
	code.val(  code.val() + tab(3) + 'echo "<p>' + oName + ' contained (".$' + frmName + '->getErrorCount().") error(s).</p>";'); 
	code.val(  code.val() + tab(3) + 'echo "<p>Errors: ".$' + frmName + '->getErrors()."</p>";'); 
	code.val(  code.val() + tab(3) + 'echo "<p><a href=\'' + oName + 'Admin.php\'>Go back to ' + oName + ' management area</a></p>";'); 
	
	code.val(  code.val() + tab(2) + '}');
	
	code.val(  code.val() + tab(1) + '}');
	code.val(  code.val() + tab(1) + 'if( $showForm == 1){');
	code.val(  code.val() + tab(0) + '?>' );
	
	
	code.val( code.val() + tab(0) + '<form name="create' + oName + '" id="create' + oName + '" method="POST" action="create' + oName +'.php" enctype="multipart/form-data">' );
	
	getFormInnards( 'CreatePage'  );
	
	code.val( code.val() + tab(1) + '<div class="formRow rowCenter">');
	code.val( code.val() + tab(2) + '<input class="button" type="submit" value="Save" /> <a href="' + oName +'Admin.php">Cancel</a>' );
	code.val( code.val() + tab(1) + '</div>');
	
	code.val( code.val() + tab(0) + '</form>');
	code.val( code.val() + tab(0) + '<?php } ?>');
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + '<?php\r\n');
		code.val( code.val() + tab(1) + 'getFooter();\r\n');
		code.val( code.val() + '?>');
	}
	
	makeCodeEditor('CreatePage', 'text/html');
}






function buildUpdateForm(){
	var code = $('#UpdatePage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	code.show();
	
	code.val(  '<?php\r\n');
	code.val( code.val() + tab(1) +	'include "include.php";\r\n');
	code.val( code.val() + tab(1) +	'include "' + oName + '.php";\r\n');
	
	
	var potentialIncludes =[];
	$('#formMode .formSection').each(function(){
		//select, selectMultiple, RadioButton Group, CheckBoxGroup
		var s = $(this).find('.item_type select[name="item"] option:selected').val(); 
		//console.log( s );
		if( s == "select" || s == "selectMultiple" || s == "radioGroup" || s == "checkGroup" ){
			var t = $(this).find('.type_list input[type="radio"]:checked').val(); 
			//console.log( t );
			if( t == "object"){
				var o = $(this).find('.type_list input[name="objectName"]').val(); 
				//console.log( o );
				if( o != ""){
					potentialIncludes.push(o);
				}
				
			}
		}
	});
	if( potentialIncludes.length > 0){
		var unique = potentialIncludes.filter( onlyUnique );
		for(var i =0; i < unique.length; i++){
			code.val( code.val() + tab(1) +	'include "' + unique[i] + '.php";\r\n');
		}
	}
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + tab(1) + 'getHeader();\r\n');
	}	
	
	code.val(  code.val() + tab(0) + '?>');
	
	code.val( code.val() + '<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Update Form: "' + oName + '" Object -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<!-- modify' + oName + '.php -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	
	
	
	
	
	
	
	code.val(  code.val() + tab(0) + '<?php');
	code.val(  code.val() + tab(1) + '$conn = getConnection(); //set to DB Conn');
	code.val(  code.val() + tab(1) + '$' + frmName + ' = new ' + oName + '($conn);');
	code.val(  code.val() + tab(1) + '$showForm = 1;');
	
	code.val(  code.val() + tab(1) + 'if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {');
	code.val(  code.val() + tab(2) + '$' + frmName + '->getFromPost();');
	code.val(  code.val() + tab(2) + '$' + frmName + '->setID( $_POST["' + frmName + 'ID"] );');
	//set the id!
	
	
	code.val(  code.val() + tab(2) + 'if( $' + frmName + '->save() > 0 && $' + frmName + '->getErrorCount() == 0){');
	
	code.val(  code.val() + tab(3) + 'echo "<p>' + oName + ' updated successfully!</p>";'); 
	code.val(  code.val() + tab(3) + 'echo "<p><a href=\'create' + oName + '.php\'>Create new ' + oName + '</a> or <a href=\'' + oName + 'Admin.php\'>Go back to ' + oName + ' management area</a></p>";'); 
	
	code.val(  code.val() + tab(3) + '$showForm = 0;');
	code.val(  code.val() + tab(2) + '}else{');
	code.val(  code.val() + tab(3) + 'echo "<p>' + oName + ' contained (".$' + frmName + '->getErrorCount().") error(s).</p>";'); 
	code.val(  code.val() + tab(3) + 'echo "<p>Errors: ".$' + frmName + '->getErrors()."</p>";'); 
	code.val(  code.val() + tab(3) + 'echo "<p><a href=\'' + oName + 'Admin.php\'>Go back to ' + oName + ' management area</a></p>";'); 
	
	
	code.val(  code.val() + tab(2) + '}');
	
	code.val(  code.val() + tab(1) + '}else{');
	code.val( code.val() + tab(2) + '$' + frmName + 'ID = $_REQUEST["' + frmName + 'ID"];\r\n');
	code.val( code.val() + tab(2) + '$' + frmName + ' = $' + frmName + '->load( $' + frmName + 'ID );\r\n');
	
	//if couldnt load echo error... 
	code.val( code.val() + tab(2) + 'if( $' + frmName + '->getID() > 0 ){');
		
	code.val( code.val() + tab(2) + '}else{');
	code.val( code.val() + tab(3) + '$showForm = 0;');
	code.val( code.val() + tab(3) + 'echo "<p>Could not load ' + oName + ' with ID of ".$' + frmName +'ID."</p>";');	
		
	code.val( code.val() + tab(2) + '}');
	
	code.val(  code.val() + tab(1) + '}');
	//check request
	
	
	
	code.val(  code.val() + tab(1) + 'if( $showForm == 1){');
	code.val(  code.val() + tab(0) + '?>' );
	
	
	code.val( code.val() + tab(0) + '<form name="modify' + oName + '" id="modify' + oName + '" method="POST" action="modify' + oName +'.php" enctype="multipart/form-data">' );
	
	getFormInnards( 'UpdatePage'  );
	
	code.val( code.val() + tab(1) + '<div class="formRow rowCenter">');
	code.val( code.val() + tab(2) + '<input type="hidden" name="' + frmName + 'ID" value="<?php echo $' + frmName + '->getID(); ?>" /> <input class="button" type="submit" value="Update" /> <a href="' + oName +'Admin.php">Cancel</a>' );
	code.val( code.val() + tab(1) + '</div>');
	
	code.val( code.val() + tab(0) + '</form>');
	code.val( code.val() + tab(0) + '<?php } ?>');
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + '<?php\r\n');
		code.val( code.val() + tab(1) + 'getFooter();\r\n');
		code.val( code.val() + '?>');
	}
	
	makeCodeEditor('UpdatePage', 'text/html');
}








function buildDeleteForm(){
	var code = $('#DeletePage');
	var variables = $('#variables');
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	code.show();
	
	code.val( '<?php\r\n');
	code.val( code.val() + tab(2) +	'include "include.php";\r\n');
	code.val( code.val() + tab(2) +	'include "' + oName + '.php";\r\n');
	
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + tab(1) + 'getHeader();\r\n');
	}	
	code.val( code.val() + '?>\r\n');
	
	code.val( code.val() + '<!--Form Generated by Brendon Irwin\'s Form Generator-->\r\n');
	code.val( code.val() + '<!--Delete Form: "' + oName + '" Object -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<!-- delete' + oName + '.php -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	
	
	code.val( code.val() + '<?php');
	code.val( code.val() + tab(2) +	'$conn = getConnection(); //create DB Connection \r\n');
	code.val( code.val() + tab(2) + '$' + frmName + ' = new ' + oName + '( $conn );\r\n');
	
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	
	code.val( code.val() + tab(2) +	'if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){\r\n');
	code.val( code.val() + tab(3) + '$' +	frmName + 'ID = $_POST["' + frmName + 'ID"];\r\n');
	
	code.val( code.val() + tab(3) + '$' + frmName + ' = $' + frmName + '->load( $' + frmName + 'ID );\r\n');
	
	code.val( code.val() + tab(3) + 'if( $' + frmName + '->delete() ){\r\n');
	code.val( code.val() + tab(4) + 'echo "<p>' + oName + ' deleted Successfully</p>";\r\n');
	code.val(  code.val() + tab(4) + 'echo "<p><a href=\'create' + oName + '.php\'>Create ' + oName + '</a> or <a href=\'' + oName + 'Admin.php\'>Go back to ' + oName + ' management area</a></p>";'); 
	
	code.val( code.val() + tab(3) + '}else{\r\n');
	code.val( code.val() + tab(4) + 'echo "<p>Error! Could not delete ' + oName + '</p>";\r\n');
	code.val(  code.val() + tab(4) + 'echo "<p><a href=\'' + oName + 'Admin.php\'>Go back to ' + oName + ' management area</a></p>";'); 
	code.val( code.val() + tab(3) + '}\r\n');
	
	code.val( code.val() + tab(2) +	'}else{\r\n');
	
	code.val( code.val() + tab(3) + '$' +	frmName + 'ID = $_REQUEST["' + frmName + 'ID"];\r\n');
	code.val( code.val() + tab(3) + '$' + frmName + ' = $' + frmName + '->load( $' + frmName + 'ID );\r\n');
	code.val( code.val() + tab(3) + 'if( $' + frmName + '->getID() > 0 ){\r\n');
	code.val( code.val() + tab(3) + '?>\r\n');
	code.val( code.val() + tab(4) + '<form method="post" action="delete' + oName + '.php">\r\n');
	
	code.val( code.val() + tab(5) + '<p>Are you sure you wish to delete ' + oName + ' with ID of: <?php  echo $' + frmName + 'ID; ?></p>\r\n');
	code.val( code.val() + tab(5) + '<input type="hidden" name="' + frmName + 'ID" value ="<?php echo $' + frmName + '->getId(); ?>"/>\r\n');
	code.val( code.val() + tab(5) + '<input type="submit" value="Yes" /> <a href="' + oName +'Admin.php">Cancel</a>\r\n');
	
	code.val( code.val() + tab(4) + '</form>\r\n');
	code.val( code.val() + tab(3) + '<?php\r\n');
	code.val( code.val() + tab(3) + '}else{\r\n');
	code.val( code.val() + tab(4) + 'echo "<p>Error! Could not load ' + oName + '</p>";\r\n');
	code.val( code.val() + tab(3) + '}\r\n');
	code.val( code.val() + tab(2) +	'}\r\n');
	code.val( code.val() + '?>\r\n');
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + '<?php\r\n');
		code.val( code.val() + tab(1) + 'getFooter();\r\n');
		code.val( code.val() + '?>');
	}
	
	makeCodeEditor('DeletePage', 'text/html');
}

function buildAjaxTable(){
	var code = $('#GenAjaxCode');
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	
	var linksClasses = 0;
	
	if( $('.formRow .type_list input[value="object"]:checked').length > 0 ){
		linksClasses = 1;
		console.log("Classes Linked");
	}
	
	code.show();
	code.val('<?php\r\n');
	code.val( code.val() + '/*\r\n');
	code.val( code.val() + 'Ajax Form Generated by Brendon Irwin\'s Form Generator\r\n');
	code.val( code.val() + 'Query Form: "' + oName + '" Object \r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + 'ajaxTable' + oName + '.php \r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '*/\r\n');
	code.val( code.val() + tab(2) +	'include "include.php";\r\n');
	
	code.val( code.val() + tab(2) +	'$type = $_GET["type"];\r\n');
	code.val( code.val() + tab(2) +	'$draw = $_GET["draw"];\r\n');
	code.val( code.val() + tab(2) +	'$start = $_GET["start"];\r\n');
	code.val( code.val() + tab(2) +	'$length =  (int)($_GET["length"]);\r\n');
	code.val( code.val() + tab(2) +	'$orderBy = (int)$_GET["order"][0]["column"];\r\n');
	code.val( code.val() + tab(2) +	'$orderDir = $_GET["order"][0]["dir"];\r\n');
	code.val( code.val() + tab(2) +	'$orderDir = ($orderDir == "asc" ? "ASC" : "DESC");\r\n');
	code.val( code.val() + tab(2) +	"$search = isset($_GET['search']['value']) ? $_GET['search']['value'] : '';\r\n");
	code.val( code.val() + tab(2) +	'if( $search != ""){\r\n');
		code.val( code.val() + tab(3) +	'$search = "%".$search."%";\r\n');
	code.val( code.val() + tab(2) +	'}\r\n');

	//code.val( code.val() + tab(2) +	'if( $start < 0 || !is_int($start) ){\r\n');
	//	code.val( code.val() + tab(3) +	'$start = 0;\r\n');
		code.val( code.val() + tab(3) +	'$start = (int)$start;\r\n');
	//code.val( code.val() + tab(2) +	'}\r\n');
		
	code.val( code.val() + tab(2) +	'$conn = getConnection();\r\n');
	
	code.val( code.val() + tab(2) +	'$query = "SELECT COUNT(`id`) as `cnt` FROM `' + frmName +'`";\r\n');
	code.val( code.val() + tab(2) +	'$result = $conn->prepare($query);\r\n');
	code.val( code.val() + tab(2) +	'$result->execute();\r\n');
	code.val( code.val() + tab(2) +	'$result = $result->fetchAll(PDO::FETCH_ASSOC);\r\n');
	code.val( code.val() + tab(2) +	"$recordsTotal = $result[0]['cnt'];\r\n");
	
	/*Order By Logic */
	code.val( code.val() + tab(2) +	'if( $orderBy != "" && is_int($orderBy) ){\r\n');
		code.val( code.val() + tab(3) +	'switch($orderBy){\r\n');
		var variables = getFormVals("form");
		var varcnt = 1;
		code.val( code.val() + tab(4) +	'case 0:\r\n');
		code.val( code.val() + tab(5) +	'$orderBy = "' + frmName +'.`id`";\r\n');
		code.val( code.val() + tab(4) +	'break;\r\n');
		
		for(var obc = 0; obc < variables.length; obc++){
			console.log(  variables[obc].showAdmin );
			if( variables[obc].showAdmin == true ){
				console.log( variables[obc].name );
				//check showAdmin
				
				code.val( code.val() + tab(4) +	'case ' + varcnt + ':\r\n');
				code.val( code.val() + tab(5) +	'$orderBy = "`' + variables[obc].name +'`";\r\n');
				code.val( code.val() + tab(4) +	'break;\r\n');
				varcnt++;
				
			}	
				
		}
			code.val( code.val() + tab(4) +	'default:\r\n');
				code.val( code.val() + tab(5) +	'$orderBy = "`id`";\r\n');
			code.val( code.val() + tab(4) +	'break;\r\n');
	
		code.val( code.val() + tab(3) +	'}\r\n');
	code.val( code.val() + tab(2) +	'}else{\r\n');
		code.val( code.val() + tab(3) +	'$orderBy = "`id`";\r\n');
	code.val( code.val() + tab(2) +	'}\r\n');
	/* Query Logic */
	//useQuery && showAdmin
	
	if( linksClasses ){
		code.val( code.val() + tab(2) +	'$query = "SELECT prTable.`id`,\r\n'); 
	}else{
		code.val( code.val() + tab(2) +	'$query = "SELECT `id`,\r\n'); 
	}
	var linkedTables = new Array(); //added Sept 5
	
	var selcount = 0;
	var selFields = "";
	for(var obc = 0; obc < variables.length; obc++){
		if( variables[obc].showAdmin == true ){
			selcount++;
			if( linksClasses ){
				//need to check if variable is from other class..
				if( variables[obc].listType == "object" ){
					selFields += ' ' + variables[obc].listObjectName + '.`' + variables[obc].listObjectTitleFunction + '` as `' +  variables[obc].name + '`,';
					//push array obj
					var to = {object: variables[obc].listObjectName, key: variables[obc].listObjectKeyFunction, map: variables[obc].name };
					linkedTables.push( to );
					
				}else{
					selFields += 'prTable.`' + variables[obc].name + '`,'; 
				}
				
			}else{
				selFields += '`' + variables[obc].name + '`,'; 
			}
			
		}
	}
	if( selcount > 0 ){
		code.val( code.val() + tab(3) + selFields.substring(0, selFields.length - 1) +   '\r\n');
	}
	code.val( code.val() + tab(2) + 'FROM\r\n');
	
	
	if( linksClasses ){
		code.val( code.val() + tab(3) + '`' + frmName + '` prTable \r\n');	
		
		//join other classes...
		if( linkedTables.length > 0){
			code.val( code.val() + '\r\n');
		}
		
		for(var tos = 0; tos < linkedTables.length; tos++){
			console.log( linkedTables[tos] );
			
			code.val( code.val() + tab(3) + 'left join `'  + linkedTables[tos].object  + '` on `' + linkedTables[tos].object + '`.`' + linkedTables[tos].key + '` = `prTable`.`' + linkedTables[tos].map + '` \r\n');	
			
		}
		
		
		
	}else{
		code.val( code.val() + tab(3) + '`' + frmName + '`\r\n');
	}
	
	
	
	code.val( code.val() + tab(2) + 'WHERE\r\n');
	//queryable?
	
	selFields = "";
	
	selFields = '".( $search != "" ? "'; 
	selcount = 0;
	for(var obc = 0; obc < variables.length; obc++){
		if( variables[obc].useQuery == true ){
			
			selFields +=  ' (`' + variables[obc].name + '` ".($search != "" ? " LIKE :SEARCH" : "").") OR'; 
	//(uf.`tags` ".($search != "" ? " LIKE :SEARCH": "").") OR 
	//(a.`alias` ".($search != "" ? " LIKE :SEARCH": "").") OR 
	//(uf.`uploader` ".($search != "" ? " LIKE :SEARCH": "").")" 
			selcount++;
		}
	}
	
	
	
	if( selcount > 0){
		selFields = selFields.substring(0, selFields.length - 3);
	}
	selFields += '" : " 1 ") ."';
		
	code.val( code.val() + tab(3) + selFields + '\r\n');
	
	
	
	code.val( code.val() + tab(2) + 'ORDER BY\r\n');
	code.val( code.val() + tab(3) + '".$orderBy." ".$orderDir."\r\n');
	code.val( code.val() + tab(2) + 'LIMIT :START,:LENGTH";\r\n');
	
	/*End Query*/
	code.val( code.val() + tab(2) +	"$result = $conn->prepare($query);\r\n");
	code.val( code.val() + tab(2) +	"$result->bindParam(':LENGTH', $length, PDO::PARAM_INT);\r\n");
	code.val( code.val() + tab(2) +	"$result->bindParam(':START', $start, PDO::PARAM_INT);\r\n");
	code.val( code.val() + tab(2) +	'if( $search != ""){\r\n');
		code.val( code.val() + tab(3) +	"$result->bindParam(':SEARCH', $search, PDO::PARAM_STR);\r\n");
	code.val( code.val() + tab(2) +	"}\r\n");
	
	code.val( code.val() + tab(2) +	"$result->execute();	\r\n");	
	
	
	code.val( code.val() + tab(2) +	"$results = $result->fetchAll(PDO::FETCH_ASSOC);\r\n");
	
	
	$data = "";
	code.val( code.val() + tab(2) +	"foreach( $results as $row){\r\n");
	    code.val( code.val() + tab(2) +	"$id = $row['id'];\r\n");
		code.val( code.val() + tab(2) +	"$data[] =  array(\r\n");
		
			//$row['id'], '<a target="_blank" href="'.WEB_ROOT.UPLOAD_FOLDER_NAME.$row['path'].'">'.$row['file'].'</a>', ($row['alias'] == "" ? "-" : $row['alias']) , ($row['active']==1?'Yes':'No'), $row['campus'], $row['category'], $row['faculty'], $row['tags'], $row['type'], $row['uploader'], ($row['expiry'] == "0000-00-00 00:00:00" ? "" : substr($row['expiry'],0, 10) ) , '<a href="deleteFile.php?fileID='.$row['id'].'&key='.hash('md5',KEY.$row['path']).'">Delete</a> <a href="modifyFile.php?fileID='.$row['id'].'&key='.hash('md5',KEY.$row['path']).'">Modify</a>'
	
	selcount = 0;
	selFields = "";
	selFields += '$row["id"], ';
	for(var obc = 0; obc < variables.length; obc++){
		if( variables[obc].showAdmin == true ){
			selFields += '$row["' + variables[obc].name + '"], ';
			selcount++;
		}
	}	
	//selFields += "'<a href=\"modify" + oName + ".php?" + frmName + "ID='.$row[\"id\"].'\">Modify</a>'";
	selFields += '"<a href=\'modify' + oName + '.php?' + frmName + 'ID=$id\'>Modify</a><a href=\'delete' + oName + '.php?' + frmName + 'ID=$id\'>Delete</a>"';

	
	//if( selcount > 0){
		//selFields = selFields.substring(0, selFields.length - 2);
	//}else{
	//	selFields = selFields.substring(0, selFields.length - 2);
	//}	
	
	
	
	//add the modify/delete links
	
	
		code.val( code.val() + tab(3) + selFields + '\r\n');	
		
		
		code.val( code.val() + tab(2) +	");\r\n");
	code.val( code.val() + tab(2) +	"}\r\n");
	
	code.val( code.val() + tab(2) +	"if( sizeof($results) == 0 ){ $data = array(); }\r\n");
	
	
	code.val( code.val() + tab(2) +	"$recordsFiltered =  sizeof( $data ) ;\r\n");
	code.val( code.val() + tab(2) +	"ob_clean();\r\n");
	//code.val( code.val() + tab(2) +	'echo json_encode( array( "draw" => (int)($draw), "recordsTotal" => $recordsTotal, "recordsFiltered" => $recordsFiltered, "data" => $data, "error" => "") ); \r\n');
	code.val( code.val() + tab(2) +	'echo json_encode( array( "draw" => (int)($draw), "recordsTotal" => $recordsTotal, "recordsFiltered" => $recordsTotal, "data" => $data, "error" => "") ); \r\n');
	code.val( code.val() + tab(2) +	"exit;\r\n");
	code.val(code.val() + '?>');
	
	
	makeCodeEditor('GenAjaxCode', "text/x-php");
}




function buildCSVTable(){
	var code = $('#ExportCode');
	
	var frmName = $('#className').val().toLowerCase().trim();
	var oName = frmName.capitalize();
	code.show();
	code.val(  '<?php\r\n');
	
	code.val( code.val() + '/* Form Generated by Brendon Irwin\'s Form Generator\r\n');
	code.val( code.val() + '<!--Create Form: "' + oName + '" Object -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '<!-- export' + oName + '.php -->\r\n');
	code.val( code.val() + '\r\n');
	code.val( code.val() + '*/\r\n');
	
	
	code.val( code.val() + tab(1) +	'include "include.php";\r\n');
	code.val( code.val() + tab(1) +	'include "' + oName + '.php";\r\n');
	
	
	code.val( code.val() + '?>\r\n');
	
	code.val( code.val() + '<?php\r\n');
	code.val( code.val() + tab(1) +	'if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){\r\n');
	code.val( code.val() + tab(1) +	'$conn = getConnection();\r\n');
	code.val( code.val() + tab(2) +	'$select = "SELECT ";');
	$('#formMode .formSection').each(function(){
		var variable = $(this).find('.item_variableName input').val();
		variable = variable.replace(/\s+/g, ' ');
		code.val( code.val() + tab(2) +	'$select = $select.(( isset($_POST["' + variable + '"]) && $_POST["' + variable + '"] == 1 ) ? "`' + variable + '`, " : "");');
	});
	//trim last character of select string
	
	//dont trim if count of select = 0
	code.val( code.val() + tab(2) +	'$select = substr($select, 0, -2);');
	
	
	code.val( code.val() + tab(2) +	'$select = $select." FROM `' + oName + '`";');
	
	//if where clause... else append;
	
	/*
	
	if( isset($_POST["addWhere"] && $_POST["addWhere"] == "Yes"){
		$count = 0;
		foreach($_POST["appendHow"] as $item){
			//appendHow -AND / OR
			//where  - variable names - check if in array of valid items...
			//operator - like, equal, gt, lt
			//filterString - string
			
			if( $count > 0){
				$select =  $select. " "
			}
			
			$count++;
		}
		
	}else{
		$select = $select.";";
	}
	
	*/
	
	code.val( code.val() + tab(2) +	'$query = $conn->prepare( $select );');
	
	code.val( code.val() + tab(2) +	'if( $query->execute() ){');
	code.val( code.val() + tab(3) +	'header("Content-type: text/csv");');
	code.val( code.val() + tab(3) +	'header("Content-Disposition: attachment; filename=export.csv");');
	code.val( code.val() + tab(3) +	'header("Pragma: no-cache");');
	code.val( code.val() + tab(3) +	'header("Expires: 0");');
	code.val( code.val() + tab(3) +	'$results = $query->fetchAll(PDO::FETCH_ASSOC);	');
	//echo each 'label with ,'
	var optionsHTML = "";
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		var variable = $(this).find('.item_variableName input').val();
		variable = variable.replace(/\s+/g, ' ');
		code.val( code.val() + tab(2) +	'echo (( isset($_POST["' + variable + '"]) && $_POST["' + variable + '"] == 1 ) ? "' + label + ', " : "");');	
		optionsHTML += '<option  value="' +  variable + '">' + label + '</option>';
	});
	code.val( code.val() + tab(3) +	'echo PHP_EOL;');
	code.val( code.val() + tab(3) +	'foreach($results as $r){');
	code.val( code.val() + tab(4) +	'echo implode(",", str_replace( ",", "", $r) ).PHP_EOL;');
	code.val( code.val() + tab(3) +	'}');
	code.val( code.val() + tab(3) +	'echo PHP_EOL;');
	code.val( code.val() + tab(3) +	'exit;');
	code.val( code.val() + tab(2) +	'}else{');
	code.val( code.val() + tab(3) +	'$error = "";');
	code.val( code.val() + tab(2) +	'}');
	//if good
	
	code.val( code.val() + tab(1) +	'}' );
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + tab(1) + 'getHeader();\r\n');
	}
	
	code.val(  code.val() + tab(0) + '?>');
	
	code.val(  code.val() + tab(0) + '<style>');
	code.val(  code.val() + tab(1) + '#clauses .clause:first-child select[name="appendHow"]{display: none; }');
	code.val(  code.val() + tab(0) + '</style>');	
	
	code.val(  code.val() + tab(0) + '<div class="toggles">');
	code.val(  code.val() + tab(1) + '<script   src="//code.jquery.com/jquery-1.12.3.js"   crossorigin="anonymous"></script>');

	code.val(  code.val() + tab(1) + '<script>');
	/////
	code.val(  code.val() + tab(2) + 'var opts = \'' + optionsHTML + '\';'); 
	code.val(  code.val() + tab(2) + 'var controls = \'<div class="remove" style="display: inline-block;">X</div>\';');
		
	code.val(  code.val() + tab(2) + '$(function(){');

			
	code.val(  code.val() + tab(3) + "$('#addClause').click(function(event){");
	//check if length > 1 and add an 'AND / OR select
	
	
	code.val(  code.val() + tab(4) + '$(\'#clauses\').append(\'<div class="clause"><select class="appendHow" name="appendHow[]"><option value="AND">AND</option><option value="OR">OR</option></select> WHERE <select name="where[]">\' + opts + \'</select> <select name="operator[]"><option value="LIKE">LIKE</option><option value="EQUAL">EQUALS</option><option value="gt">Greater Than</option><option value="lt">Less Than</option></select> <input name="filterString[]" /><div class="controls">\' + controls + \'</div></div>\');');
	code.val(  code.val() + tab(4) + '$(".remove").unbind().click(function(){ $(this).parent().parent().remove(); });');	
	code.val(  code.val() + tab(4) + 'return false;');
	code.val(  code.val() + tab(3) + '});');
	
	code.val(  code.val() + tab(3) + '$(\'input[name="addWhere"]\').change(function(){ if($(this).val() == "Yes"){ $("#whereClause").show(); }else{ $("#whereClause").hide(); } }); ');
	
	
	code.val(  code.val() + tab(2) + '});');
	code.val(  code.val() + tab(1) + '</script>');
	
	
	code.val(  code.val() + tab(1) + '<form class="toggles" method="POST" action="export' + oName +'.php">');
	
	
	code.val(  code.val() + tab(2) + '<p>Check the following boxes to add them to the report:</p>');
	//code.val(  code.val() + tab(0) + '<?php');
	$('#formMode .formSection').each(function(){
		var label = $(this).find('.item_label input').val();
		var variable = $(this).find('.item_variableName input').val();
		variable = variable.replace(/\s+/g, ' ');
	
		code.val(  code.val() + tab(2) + '<input type="checkbox" name="' + variable + '" value="1" <?php echo ( isset($_POST["' + variable + '"]) && $_POST["' + variable + '"] == 1 ) ? "checked" : ""; ?>/>: ' + label + '<br />');
	});	
	//toggles
	code.val(  code.val() + tab(2) + '<p>Configure where clause? <input type="radio" name="addWhere" value="Yes" />Yes <input type="radio" name="addWhere" value="No" /> No </p>');
	code.val(  code.val() + tab(2) + '<fieldset id="whereClause" style="display: none;">');
	code.val(  code.val() + tab(3) + '<legend>Filter Data - Where</legend>');
	
	
	code.val(  code.val() + tab(3) + '<div id="clauses"></div>');
	
	code.val(  code.val() + tab(3) + '<button id="addClause">Add Clause</button>');
	
	
	code.val(  code.val() + tab(2) + '</fieldset>');
	
	
	
	
	
	code.val(  code.val() + tab(2) + '<p><input type="submit" value="GENERATE CSV"/></p>');
	code.val(  code.val() + tab(1) + '</form>');
	code.val(  code.val() + tab(0) + '</div>');
	
	if( $('#headerfooter').prop('checked') == true ){
		code.val( code.val() + '<?php\r\n');
		code.val( code.val() + tab(1) + 'getFooter();\r\n');
		code.val( code.val() + '?>\r\n');
	}
	
	makeCodeEditor('ExportCode', "text/x-php");
	//show toggles for what to download
	
	//on submit echo file
}























